# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

softimpute_cpp <- function(X, mask, lambdas, tol, maxiter) {
    .Call('_GenSoftImpute_softimpute_cpp', PACKAGE = 'GenSoftImpute', X, mask, lambdas, tol, maxiter)
}

gensoftimpute_cpp <- function(X, M, W, mask, lambdas, tol, maxiter) {
    .Call('_GenSoftImpute_gensoftimpute_cpp', PACKAGE = 'GenSoftImpute', X, M, W, mask, lambdas, tol, maxiter)
}

gen_svd_for_R <- function(X, M, W) {
    .Call('_GenSoftImpute_gen_svd_for_R', PACKAGE = 'GenSoftImpute', X, M, W)
}

